config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  resources :weathers
  resources :cities do
    resources :events, only: [:index, :show]
  end

  # Rotte personalizzate per il HomeController
  post 'search_trip', to: 'home#search_trip'
  get 'suggest_cities', to: 'home#suggest_cities'

  get 'search_city', to: 'home#search_city', as: 'search_city'

  # Imposta la tua nuova pagina principale come root
  root 'home#index'

  # Definisci la rotta per la verifica dello stato di salute dell'applicazione
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/controllers/home_controller.rb
require 'uri'
class HomeController < ApplicationController
  def index
    @cities=City.all
  end

  def search_trip
    # Logica per elaborare la ricerca del viaggio
    departure_city = params[:departure_city]
    destination_city = params[:destination_city]
    departure_date = params[:departure_date]
    number_of_people = params[:number_of_people]
    number_of_infants=params[:number_of_infants]
    number_of_children=params[:number_of_children]
    round_trip = params[:round_trip]
    return_date = params[:return_date]

    # Esegui le azioni necessarie con questi dati
    redirect_to root_path, notice: "Trip search submitted!"
  end

  def search_city
    # Logica per elaborare la ricerca della città
    city_name = params[:city_name]
   # Rails.logger.debug "Redirecting to: #{cities_path(query: city_name)}"
   redirect_to cities_path(query: city_name)

  end

  def suggest_cities
    # Logica per ottenere i suggerimenti delle città
    query = params[:query]
    @cities = City.where("name LIKE ?", "#{query}%").limit(5)

    respond_to do |format|
      format.json { render json: @cities.select(:id, :name) }
    end
  end
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Cheap Traveler</title>
</head>
</html>

<!-- app/views/pages/home.html.erb -->

<h1>Search your trip</h1>

<form action="/search_trip" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <div>
    <label for="departure_city">Departure city:</label>
    <input type="text" id="departure_city" name="departure_city" required onkeyup="suggestCities(this.value, 'departure_suggestions', 'departure_city')">
    <ul id="departure_suggestions" class="suggestions"></ul>
  </div>

  <div>
    <label for="destination_city">Destination city:</label>
    <input type="text" id="destination_city" name="destination_city" required onkeyup="suggestCities(this.value, 'destination_suggestions', 'destination_city')">
    <ul id="destination_suggestions" class="suggestions"></ul>
  </div>

  <div>
    <label for="departure_date">Departure date:</label>
    <input type="date" id="departure_date" name="departure_date" required>
  </div>

  <div>
    <label for="number_of_people">Number of adults:</label>
    <input type="number" id="number_of_people" name="number_of_people" min="1" required>
  </div>
  <div>
    <label for="number_of_children">Number of children:</label>
    <input type="number" id="number_of_children" name="number_of_children" min="0" required>
  </div>

  <div>
    <label for="number_of_infants">Number of infants:</label>
    <input type="number" id="number_of_infants" name="number_of_infants" min="0" required>
  </div>
  <div>
    <input type="checkbox" id="round_trip" name="round_trip" value="yes" onclick="toggleReturnDate()">
    <label for="round_trip">Roundtrip</label>
  </div>

  <div id="return_date_div" style="display:none;">
    <label for="return_date">Return date:</label>
    <input type="date" id="return_date" name="return_date">
  </div>

  <div>
    <input type="submit" value="Cerca">
  </div>
</form>

<h2>Search city</h2>

<form action="<%= search_city_path %>" method="get">
  <div>
    <label for="city_name">Search city by name:</label>
    <input type="text" id="city_name" name="city_name" required onkeyup="suggestCities(this.value, 'city_suggestions', 'city_name')">
    <ul id="city_suggestions" class="suggestions"></ul>
    <input type="submit" value="Cerca">
  </div>
</form>

<script>
  function toggleReturnDate() {
    var roundTripCheckbox = document.getElementById('round_trip');
    var returnDateDiv = document.getElementById('return_date_div');
    if (roundTripCheckbox.checked) {
      returnDateDiv.style.display = 'block';
    } else {
      returnDateDiv.style.display = 'none';
    }
  }

  function suggestCities(query, suggestionListId, inputId) {
    if (query.length === 0) {
      document.getElementById(suggestionListId).innerHTML = "";
      return;
    }

    fetch(`/suggest_cities?query=${query}`)
      .then(response => response.json())
      .then(data => {
        const suggestionList = document.getElementById(suggestionListId);
        suggestionList.innerHTML = "";

        data.forEach(city => {
          const suggestionItem = document.createElement('li');
          suggestionItem.textContent = city.name;
          suggestionItem.onclick = () => {
            document.getElementById(inputId).value = city.name;
            suggestionList.innerHTML = "";
          };
          suggestionList.appendChild(suggestionItem);
        });
      });
  }
</script>


<style>
  .suggestions {
    list-style-type: none;
    padding: 0;
    margin: 0;
    border: 1px solid;
    max-width: 200px;
    position: absolute;
    background: white;
  }
  .suggestions li {
    padding: 8px;
    cursor: pointer;
  }
  .suggestions li:hover {
    background-color:
  }
</style>