config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  resources :weathers
  resources :cities do
    resources :events, only: [:index, :show]
  end

  # Rotte personalizzate per il HomeController
  post 'search_trip', to: 'home#search_trip'
  get 'suggest_cities', to: 'home#suggest_cities'

  get 'search_city', to: 'home#search_city', as: 'search_city'

  # Imposta la tua nuova pagina principale come root
  root 'home#index'

  # Definisci la rotta per la verifica dello stato di salute dell'applicazione
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :city
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :set_city
  # GET /events or /events.json
  def index
    @events = @city.events
  end

  # GET /events/1 or /events/1.json
  def show
      
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :city_id)
    end
    def set_city
        @city = City.find(params[:city_id])
      end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <h3><%= link_to event.name, city_event_path(@city, event) %></h3>
  <p>Date: <%= event.event_date.strftime("%B %d, %Y %H:%M") %></p>
  
  <% if event.end_date.present? %>
    <p>End Date: <%= event.end_date.strftime("%B %d, %Y %H:%M") %></p>
  <% else %>
    <p>End Date: Non specificato</p>
  <% end %>
  
  <p>Description: <%= event.description %></p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.label :city_id, style: "display: block" %>
    <%= form.text_field :city_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Events</h1>

<div id="events">
  <% @events.each do |event| %>
    <%= render event%>
    
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @event.name %></h1>
<p>Start Date: <%= @event.event_date.strftime("%B %d, %Y %H:%M") %></p>
<p>Description: <%= @event.description %></p>
<p>Link: <%= link_to @event.link, @event.link %></p>