config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  resources :weathers
  resources :cities do
    resources :events, only: [:index, :show]
  end

  # Rotte personalizzate per il HomeController
  post 'search_trip', to: 'home#search_trip'
  get 'suggest_cities', to: 'home#suggest_cities'

  get 'search_city', to: 'home#search_city', as: 'search_city'

  # Imposta la tua nuova pagina principale come root
  root 'home#index'

  # Definisci la rotta per la verifica dello stato di salute dell'applicazione
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/city.rb
require 'net/http'
require 'json'
require 'geocoder'

class City < ApplicationRecord
  has_many :photos, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :weathers, dependent: :destroy



  def fetch_images_from_unsplash
    response = HTTParty.get("https://api.unsplash.com/search/photos", {
      query: {
        query: self.name,
        client_id: ENV['UNSPLASH_ACCESS_KEY'],
        per_page: 20
      }
    })

    if response.success?
      self.photos.destroy_all
      response['results'].each do |photo_data|
        self.photos.create!(image_url: photo_data['urls']['regular'])
      end
     end

  end

    require 'uri'

    def fetch_events_from_rapidapi
      url = "https://real-time-events-search.p.rapidapi.com/search-events"
      query_params = {
        query: URI.encode_www_form_component(self.name)
      }

      headers = {
        "X-RapidAPI-Host" => "real-time-events-search.p.rapidapi.com",
        "X-RapidAPI-Key" => ENV['EVENTS_KEY']
      }

      response = HTTParty.get(url, query: query_params, headers: headers)

      if response.success?
        parsed_response = JSON.parse(response.body)
        events_data = parsed_response['data']

        self.events.destroy_all  # Elimina gli eventi esistenti

        events_data.each do |event_data|
          name = event_data['name']
          description = event_data['description']
          description=description.gsub(/[^a-zA-Z0-9\s.,&-]/, '')
          start_time = DateTime.parse(event_data['start_time'])
          link=event_data['link']
          if event_data['end_time'].present?
              end_date = DateTime.parse(event_data['end_time'])
          else
            end_date = nil
          end

          entity_id=event_data['event_id']

          event = self.events.new(
                                  entity_id:entity_id,
                                  name: name,
                                  description: description,
                                  event_date: start_time,
                                  end_date: end_date,
                                  link:link
          )

          event.save  # Salva l'evento nel database
        end
      else
        puts "Errore durante la richiesta all'API: #{response.code} - #{response.message}"
      end
   end

   def fetch_weather
    url = URI("https://ai-weather-by-meteosource.p.rapidapi.com/current?lat=#{self.latitude}&lon=#{self.longitude}&timezone=auto&language=en&units=auto")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(url)
    request["X-RapidAPI-Key"] = 'da03b8da1amshe251ccba685cddap18f4e9jsnd1f33d6c395a'  # Sostituisci con la tua chiave API
    request["X-RapidAPI-Host"] = 'ai-weather-by-meteosource.p.rapidapi.com'

    response = http.request(request)
    weather_data = JSON.parse(response.body)

    if response.is_a?(Net::HTTPSuccess)
      puts weather_data  # inserita per vedere l'intero dato ricevuto
      current_weather = weather_data['current']
      {
        temperature: current_weather['temperature'],
        description: current_weather['summary'],
        datetime: current_weather['time']  #
      }
    else
      { error: weather_data['message'] }
    end
  end





end

app/controllers/cities_controller.rb
require 'httparty'
class CitiesController < ApplicationController
  before_action :set_city, only: %i[ show edit update destroy ]

  # GET /cities or /cities.json
  def index
    @query = params[:query]
    if @query.present?
      @cities = City.where("name LIKE ?", "%#{@query}%")
    else
      @cities = City.all
    end
  end
  def show
      @city = City.find(params[:id])
      @city.fetch_images_from_unsplash
      #@city.fetch_events_from_rapidapi commentata perchè sennò finivamo le richieste disponibili gratis
      @weather = @city.fetch_weather

      if @weather[:error]
        flash[:alert] = "Could not fetch weather data: #{@weather[:error]}"
      end
  end 
  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to city_url(@city), notice: "City was successfully created." }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to city_url(@city), notice: "City was successfully updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy!

    respond_to do |format|
      format.html { redirect_to cities_url, notice: "City was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:name, :country, :code)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_city.html.erb
<div id="<%= dom_id city %>">
  <p>
    <strong>Name:</strong>
    <%= city.name %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= city.country %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= city.code %>
  </p>

</div>

app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
  <% if city.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Show this city", @city %> |
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/index.html.erb
<!-- app/views/cities/index.html.erb -->
<p style="color: green"><%= notice %></p>

<h1>Cities</h1>

<div id="cities" class="city-grid">
  <% @cities.each do |city| %>
    <div class="city-item">
     <%= render city %> 
     
      <p>
        <%= link_to "Mostra dettagli", city %>
      </p>


      
    </div>
  <% end %>
</div>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render "form", city: @city %>

<br>

<div>
  <%= link_to "Back to cities", cities_path %>
</div>

app/views/cities/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%=@city.name + ", " + @city.country%> </h1>


<div class="central-column">
  <h2><%=link_to "Events",city_events_path(@city) %></h2>
  <% @city.events.order(event_date: :asc).limit(3).each do |event| %>
    <div class="event-item">
       <h3><%= link_to event.name, city_event_path(@city, event) %></h3>
      <p>Date: <%= event.event_date.strftime("%B %d, %Y  %H:%M") %></p>
      <!-- Aggiungi altre informazioni sull'evento se necessario -->
    </div>
  <% end %>
</div>


<% if @city.photos.any? %>
<!-- Aggiunta della footer per le foto -->
<footer>
  <div id="carouselExampleIndicators" class="carousel slide footer-photos" data-ride="carousel">
    <ol class="carousel-indicators">
      <% @city.photos.each_with_index do |photo, index| %>
        <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></li>
      <% end %>
    </ol>
    <div class="carousel-inner">
      <% @city.photos.each_with_index do |photo, index| %>
        <div class="carousel-item <%= 'active' if index == 0 %>">
          <%= image_tag photo.image_url, alt: @city.name, class: "d-block w-100" %>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</footer>
<% end %>


<!-- Sezione Meteo -->
<% if @weather[:error] %>
  <p><%= @weather[:error] %></p>
<% else %>
  <p>Temperatura: <%= @weather[:temperature] %>°C</p>
  <p>Descrizione: <%= @weather[:description] %></p>
  <p>Datetime: <%= @weather[:datetime] %></p>
<% end %>


<!-- Inizio del commento 
<div>
  <%= link_to "Edit this city", edit_city_path(@city) %> |
  <%= link_to "Back to cities", cities_path %>

  <%= button_to "Destroy this city", @city, method: :delete %>
</div>
fine del commento -->