config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  resources :weathers
  resources :cities do
    resources :events, only: [:index, :show]
  end

  # Rotte personalizzate per il HomeController
  post 'search_trip', to: 'home#search_trip'
  get 'suggest_cities', to: 'home#suggest_cities'

  get 'search_city', to: 'home#search_city', as: 'search_city'

  # Imposta la tua nuova pagina principale come root
  root 'home#index'

  # Definisci la rotta per la verifica dello stato di salute dell'applicazione
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/weather.rb
class Weather < ApplicationRecord
  belongs_to :city
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  before_action :set_weather, only: %i[ show edit update destroy ]

  # GET /weathers or /weathers.json
  def index
    @weathers = Weather.all
  end

  # GET /weathers/1 or /weathers/1.json
  def show
  end

  # GET /weathers/new
  def new
    @weather = Weather.new
  end

  # GET /weathers/1/edit
  def edit
  end

  # POST /weathers or /weathers.json
  def create
    @weather = Weather.new(weather_params)

    respond_to do |format|
      if @weather.save
        format.html { redirect_to weather_url(@weather), notice: "Weather was successfully created." }
        format.json { render :show, status: :created, location: @weather }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weathers/1 or /weathers/1.json
  def update
    respond_to do |format|
      if @weather.update(weather_params)
        format.html { redirect_to weather_url(@weather), notice: "Weather was successfully updated." }
        format.json { render :show, status: :ok, location: @weather }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weathers/1 or /weathers/1.json
  def destroy
    @weather.destroy!

    respond_to do |format|
      format.html { redirect_to weathers_url, notice: "Weather was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather
      @weather = Weather.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def weather_params
      params.require(:weather).permit(:city_id, :temperature, :description, :datetime)
    end
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/weathers/_form.html.erb
<%= form_with(model: weather) do |form| %>
  <% if weather.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(weather.errors.count, "error") %> prohibited this weather from being saved:</h2>

      <ul>
        <% weather.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :city_id, style: "display: block" %>
    <%= form.text_field :city_id %>
  </div>

  <div>
    <%= form.label :temperature, style: "display: block" %>
    <%= form.text_field :temperature %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :datetime, style: "display: block" %>
    <%= form.datetime_field :datetime %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/weathers/_weather.html.erb
<div id="<%= dom_id weather %>">
  <p>
    <strong>City:</strong>
    <%= weather.city_id %>
  </p>

  <p>
    <strong>Temperature:</strong>
    <%= weather.temperature %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= weather.description %>
  </p>

  <p>
    <strong>Datetime:</strong>
    <%= weather.datetime %>
  </p>

</div>

app/views/weathers/edit.html.erb
<h1>Editing weather</h1>

<%= render "form", weather: @weather %>

<br>

<div>
  <%= link_to "Show this weather", @weather %> |
  <%= link_to "Back to weathers", weathers_path %>
</div>

app/views/weathers/index.html.erb
<!-- app/views/weathers/index.html.erb -->
<h1>Weathers for <%= @city.name %></h1>

<table>
  <thead>
    <tr>
      <th>Temperature</th>
      <th>Description</th>
      <th>Date and Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weathers.each do |weather| %>
      <tr>
        <td><%= weather.temperature %></td>
        <td><%= weather.description %></td>
        <td><%= weather.datetime.strftime("%B %d, %Y %H:%M") %></td>
        <td><%= link_to 'Show', city_weather_path(@city, weather) %></td>
        <td><%= link_to 'Edit', edit_city_weather_path(@city, weather) %></td>
        <td><%= link_to 'Destroy', city_weather_path(@city, weather), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Weather', new_city_weather_path(@city) %>

app/views/weathers/new.html.erb
<h1>New weather</h1>

<%= render "form", weather: @weather %>

<br>

<div>
  <%= link_to "Back to weathers", weathers_path %>
</div>

app/views/weathers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @weather %>

<div>
  <%= link_to "Edit this weather", edit_weather_path(@weather) %> |
  <%= link_to "Back to weathers", weathers_path %>

  <%= button_to "Destroy this weather", @weather, method: :delete %>
</div>